name: TicketManager
version: 12.1.1
main: com.github.hoshikurama.ticketmanager.spigot.SpigotPlugin
api-version: 1.21
authors: [HoshiKurama]
depend: [TicketManagerCore]
softdepend: [LuckPerms]
permissions:
  ticketmanager.command.assign:
    description: Assign a ticket
    default: false
  ticketmanager.command.close.all:
    description: Close any ticket
    default: false
  ticketmanager.command.close.own:
    description: Close only own tickets
    default: false
  ticketmanager.command.closeAll:
    description: Mass close tickets
    default: false
  ticketmanager.command.comment.all:
    description: Comment on any ticket
    default: false
  ticketmanager.command.comment.own:
    description: Comment on only own tickets
    default: false
  ticketmanager.command.create:
    description: Create a ticket
    default: false
  ticketmanager.command.help:
    description: See list of ticket commands to which user has permissions for
    default: false
  ticketmanager.command.history.all:
    description: View all users' histories of tickets
    default: false
  ticketmanager.command.history.own:
    description: View own history of tickets
    default: false
  ticketmanager.command.list:
    description: List all open tickets
    default: false
  ticketmanager.command.reload:
    description: Restarts plugin
    default: false
  ticketmanager.command.reopen:
    description: Reopen any ticket
    default: false
  ticketmanager.command.search:
    description: Search database for certain tickets
    default: false
  ticketmanager.command.setPriority:
    description: Set priority of any ticket
    default: false
  ticketmanager.command.teleport:
    description: Teleport to any ticket created on the same server
    default: false
  ticketmanager.command.proxyteleport:
    description: Teleport to tickets across an entire proxy network
    default: false
  ticketmanager.command.view.all:
    description: View any ticket
    default: false
  ticketmanager.command.view.own:
    description: View own ticket
    default: false
  ticketmanager.command.viewdeep.all:
    description: View any detailed ticket
    default: false
  ticketmanager.command.viewdeep.own:
    description: View own detailed ticket information
    default: false
  ticketmanager.commandArg.cooldown.override:
    description: Overrides cooldown if enabled
    default: false
  ticketmanager.commandArg.silence:
    description: Ability to perform silent variations
    default: false
  ticketmanager.notify.openTickets.onJoin:
    description: See open and assigned ticket count on login
    default: false
  ticketmanager.notify.openTickets.scheduled:
    description: See open and assigned ticket count at scheduled intervals
    default: false
  ticketmanager.notify.unreadUpdates.onJoin:
    description: See own tickets with updates on login
    default: false
  ticketmanager.notify.unreadUpdates.scheduled:
    description: See own tickets with updates at scheduled intervals
    default: false
  ticketmanager.notify.info:
    description: See general TicketManager information
    default: false
  ticketmanager.notify.pluginUpdate:
    description: Get notified of plugin update on login
    default: false
  ticketmanager.notify.proxyUpdate:
    description: Get notified of proxy update on login
    default: false
  ticketmanager.notify.error.stacktrace:
    description: See modified stacktrace on errors
    default: false
  ticketmanager.notify.error.message:
    description: See when errors occur
    default: false
  ticketmanager.notify.change.assign:
    description: Creator sees when user assigned their ticket
    default: false
  ticketmanager.notify.change.comment:
    description: Creator sees when user comments on their ticket
    default: false
  ticketmanager.notify.change.close:
    description: Creator sees when user closes their ticket
    default: false
  ticketmanager.notify.change.massClose:
    description: Creator sees when user mass-closes their ticket
    default: false
  ticketmanager.notify.change.reopen:
    description: Creator sees when user reopens their ticket
    default: false
  ticketmanager.notify.change.priority:
    description: Creator sees when user changes their ticket priority
    default: false
  ticketmanager.notify.massNotify.assign:
    description: See ticket assignment events
    default: false
  ticketmanager.notify.massNotify.close:
    description: See any ticket close events
    default: false
  ticketmanager.notify.massNotify.comment:
    description: See any ticket comment events
    default: false
  ticketmanager.notify.massNotify.create:
    description: See ticket creation events
    default: false
  ticketmanager.notify.massNotify.massClose:
    description: See ticket mass close events
    default: false
  ticketmanager.notify.massNotify.priority:
    description: See ticket priority change events
    default: false
  ticketmanager.notify.massNotify.reopen:
    description: See ticket reopen events
    default: false
  ticketmanager.command.*:
    description: Wildcard for all commands and commandargs
    children:
      ticketmanager.command.assign: true
      ticketmanager.command.close.all: true
      ticketmanager.command.close.own: true
      ticketmanager.command.closeAll: true
      ticketmanager.command.comment.all: true
      ticketmanager.command.comment.own: true
      ticketmanager.command.create: true
      ticketmanager.command.help: true
      ticketmanager.command.history.all: true
      ticketmanager.command.history.own: true
      ticketmanager.command.list: true
      ticketmanager.command.reload: true
      ticketmanager.command.reopen: true
      ticketmanager.command.search: true
      ticketmanager.command.setPriority: true
      ticketmanager.command.teleport: true
      ticketmanager.command.proxyteleport: true
      ticketmanager.command.view.all: true
      ticketmanager.command.view.own: true
      ticketmanager.command.viewdeep.all: true
      ticketmanager.command.viewdeep.own: true
    default: false
  ticketmanager.notify.change.*:
    description: Wildcard for all status changes on own ticket
    children:
      ticketmanager.notify.change.assign: true
      ticketmanager.notify.change.comment: true
      ticketmanager.notify.change.close: true
      ticketmanager.notify.change.massclose: true
      ticketmanager.notify.change.reopen: true
      ticketmanager.notify.change.priority: true
    default: false
  ticketmanager.massNotify.*:
    description: Wildcard for all mass notifications (except errors and plugin info)
    children:
      ticketmanager.notify.massNotify.assign: true
      ticketmanager.notify.massNotify.close: true
      ticketmanager.notify.massNotify.comment: true
      ticketmanager.notify.massNotify.create: true
      ticketmanager.notify.massNotify.massClose: true
      ticketmanager.notify.massNotify.priority: true
      ticketmanager.notify.massNotify.reopen: true
    default: false
  ticketmanager.notify.*:
    description: Wildcard for all notification permissions
    children:
      ticketmanager.notify.openTickets.onJoin: true
      ticketmanager.notify.openTickets.scheduled: true
      ticketmanager.notify.unreadUpdates.onJoin: true
      ticketmanager.notify.unreadUpdates.scheduled: true
      ticketmanager.notify.error.stacktrace: true
      ticketmanager.notify.error.message: true
      ticketmanager.notify.info: true
      ticketmanager.massNotify.*: true
      ticketmanager.notify.change.*: true
      ticketmanager.notify.pluginUpdate: true
      ticketmanager.notify.proxyUpdate: true
    default: false
  ticketmanager.*:
    description: Wildcard for all TicketManager permissions
    children:
      ticketmanager.notify.*: true
      ticketmanager.command.*: true
      ticketmanager.commandArg.cooldown.override: true
      ticketmanager.commandArg.silence: true
    default: op
  ticketmanager.basic:
    description: Preset for normal users
    children:
      ticketmanager.command.close.own: true
      ticketmanager.command.comment.own: true
      ticketmanager.command.create: true
      ticketmanager.command.help: true
      ticketmanager.command.history.own: true
      ticketmanager.command.view.own: true
      ticketmanager.notify.unreadUpdates.onJoin: true
      ticketmanager.notify.unreadUpdates.scheduled: true
      ticketmanager.notify.change.*: true
    default: false
  ticketmanager.manage:
    description: Preset for staff (includes ticketmanager.basic)
    children:
      ticketmanager.basic: true
      ticketmanager.command.assign: true
      ticketmanager.command.close.all: true
      ticketmanager.command.comment.all: true
      ticketmanager.command.list: true
      ticketmanager.command.reopen: true
      ticketmanager.command.search: true
      ticketmanager.command.setPriority: true
      ticketmanager.command.view.all: true
      ticketmanager.command.viewdeep.all: true
      ticketmanager.command.viewdeep.own: true
      ticketmanager.command.history.all: true
      ticketmanager.commandArg.cooldown.override: true
      ticketmanager.notify.openTickets.onJoin: true
      ticketmanager.notify.openTickets.scheduled: true
      ticketmanager.notify.info: true
      ticketmanager.massNotify.*: true
    default: false